<?php

// Lightflows simple social button

function simple_social_init()
{
drupal_add_js('http://apis.google.com/js/plusone.js');
}

function simple_social_render($nid)
{
	//$fb = simple_social_facebook_button($nid);
	$fb = simple_social_facebook_button_new();
	$twitter = simple_social_twitter_button($nid);
	$gplus = simple_social_gplus();
	$output;
	
	$output .= '<div class="social clearfix">';
	$output .= $twitter;
	$output .= $gplus;
	$output .= $fb;
	$output .= '</div>';
	print $output;
}

function simple_social_facebook_button($nid)
{
	global $base_url;
	$node = node_load($nid);
	$alias = drupal_get_path_alias( 'node/' . $node->nid);
	$url = $base_url.'/'.$alias;
	
	$output = '<div class="social">';
	$output .= '<div class="fb_like"><iframe src="http://www.facebook.com/plugins/like.php?href='.$url.'&amp;layout=button_count&amp;show_faces=true&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:90px; height:21px;" allowTransparency="true"></iframe>';
	$output .= '</div>';
	return $output;
}

function simple_social_facebook_button_new()
{
	$output = '<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#appId=136328626451722&amp;xfbml=1"></script><fb:like href="" send="true" width="260" show_faces="true" font="arial"></fb:like>';
	return $output;
}

function simple_social_gplus()
{
	$output = '<div class="googlePlus">';
	$output .= '<g:plusone></g:plusone>';
	$output .= '</div>';
	return $output;
}

function simple_social_twitter_button($nid)
{
	global $base_url;
	$node = node_load($nid);
	$text = 'Check out this super offer from '.$node->title;
	$alias = drupal_get_path_alias( 'node/' . $node->nid);
	$url = $base_url.'/'.$alias;

	$urlEncode = urlencode($url);
	$output = '<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>';
	$output .= '<div class="tweetbutton">';
	$output .= '<a href="http://twitter.com/share?url='.$urlEncode.'&amp;counturl='.$urlEncode.'&amp;text='.$text.'&amp;via=lovedressage" class="twitter-share-button">Tweet</a></div>';
	return $output;
}